version: '3'
services:
  db:
    image: postgres
    container_name: todo
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
